apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenoid
  template:
    metadata:
      labels:
        app: selenoid
    spec:
      containers:
        - name: selenoid
          image: aerokube/selenoid:latest
          args: ["-container-network", "nbank-network"]
          ports:
            - containerPort: 4444
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: selenoid-config
              mountPath: /etc/selenoid
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: selenoid-config
          configMap:
            name: selenoid-config
---
apiVersion: v1
kind: Service
metadata:
  name: selenoid
  labels:
    app: selenoid
spec:
  selector:
    app: selenoid
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
  type: NodePort

