name: Run tests

on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Set up services
        run: cd infra/dockercompose && bash restart-docker.sh && cd ../..

      - name: Show running containers
        run: docker ps -a

      - name: Show backend logs
        run: docker logs $(docker ps -qf "ancestor=nobugsme/nbank:with_username_error_fix") || true

      - name: Show frontend logs
        run: docker logs $(docker ps -qf "ancestor=nobugsme/nbank-ui:with_nginx") || true

      - name: Run tests
        run: ./mvnw clean test -q