name: Run tests

on: [ push, workflow_dispatch]

jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Set up services
        run: |
          cd infra/dockercompose
          bash restart-docker.sh
          cd ../..

      - name: Install dockerize
        run: |
          curl -sSL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
          | sudo tar -C /usr/local/bin -xz

      - name: Wait for services
        run: |
          dockerize -wait http://localhost:4111 -timeout 60s

      - name: Run tests
        run: ./mvnw clean test -q