version: "3.9"

services:
  backend:
    image: nobugsme/nbank:with_validation_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4111/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: nobugsme/nbank-ui:latest
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: ["-container-network", "nbank-network"]
    depends_on:
      frontend:
        condition: service_healthy
    networks:
      - nbank-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 10s
      timeout: 5s
      retries: 10

  test-runner:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      backend:
        condition: service_healthy
      selenoid:
        condition: service_healthy
    networks:
      - nbank-network
    command: mvn clean test -P api

networks:
  nbank-network:
    name: nbank-network
